### ISSUE TITLE
AW Admin Facelift

### ISSUE THREAD

**Issue by gsteimer** [tsgrp/ActiveWizard#248]
The AW Admin is TSG oldest running codebase (first started in 2002!).  Although we'd eventually like to rewrite it as part of the HPI admin, that's a very large undertaking.  In the meantime, it would be good to give the admin a small facelift.  Here are some things I think we should do:

**Phase 1**
Make the current functionality work better in chrome and IE10+
- [x] The dropdowns are old YUI and don't work at all in chrome.  We can either get them to work, or replace them with more modern controls.  As with HPI, the existing functionality should be there - users can start typing OR use a pull down menu to see all options.
- [x] Disabled buttons in Chrome don't look any different than enabled buttons.  This causes some buttons to look clickable, but really aren't.
- [x] When editing a page, the tree view on the left should expand.  In chrome currently, it does not.  I'm fine if the whole tree expands or just the first level (questions)

**Phase 2**
- [x] More modern look and feel with Bootstrap 3
- [x] Update page instructions to be more helpful, remove unnecessary information
- [x] Update HTML text instructions - still Flex-specific
- [x] Remove sections of the AW Admin that are either not yet implemented or out of date (just comment out the ability, don't completely remove the functionality):
  - [x] Repeat Page Action
  - [x] Include Outlook Contact Drop Area - Page Option
  - [x] Reference Label and Reference Link - Page Options
  - [x] Reference Label and Reference Link - Question Options
  - [x] Group question required and Group Question Disabled - Page Options
  - [x] Existing Values section - Question
  - [x] Existing Values section - Answer
  - [x] Answer Actions:
    - [x] Link Form
    - [x] Answer Filter
    - [x] Run a query (as a **question action only**)

**Comment by ghost** [comment]
Phase 2 fixed locally, will commit tomorrow after a CR

**Comment by ghost** [comment]
Face Lift finished.
HPI AW Admin - 7662
CR - Dan G

**Comment by gsteimer** [comment]
Updated incorrect removal of the 'Run a Query' action from answers.  Instead, remove the action from questions.

AW Admin Rev 7664
